apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: auth
  template:
    metadata:
      labels:
        apps: auth
    spec:
      containers:
        - name: auth
          image: unglued/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    apps: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
