apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: client
  template:
    metadata:
      labels:
        apps: client
    spec:
      containers:
        - name: client
          image: unglued/client
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    apps: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
