apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: tickets
  template:
    metadata:
      labels:
        apps: tickets
    spec:
      containers:
        - name: tickets
          image: unglued/tickets
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    apps: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
